cabal-version:      3.0
name:               ubi-launch
version:            0.1.0.0
-- synopsis:
-- description:
license:            LGPL-3.0-or-later
license-file:       LICENSE
author:             Abastro
maintainer:         abab9579@gmail.com
copyright:          2024 Abastro
category:           System
build-type:         Simple
extra-doc-files:
  CHANGELOG.md

-- Extra source files to be distributed with the package, such as examples, or a tutorial module.
-- extra-source-files:

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:
        Command
        Detect.Autocomplete
        Detect.Help
    build-depends:
        base ^>=4.17.2.1,
        vector,
        text,
        bytestring,
        containers,
    hs-source-dirs:   src
    default-language: GHC2021

executable ubi-launch
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base ^>=4.17.2.1,
        ubi-launch
    hs-source-dirs:   app
    default-language: GHC2021
